(include_subdirs unqualified)

(rule
 (targets c_flags.sexp)
 (action
  (with-stdout-to
   c_flags.sexp
   (system "echo -n '('; pkg-config --cflags sdl2 glew; echo -n ')'"))))

(rule
 (targets c_library.sexp)
 (action
  (with-stdout-to
   c_library.sexp
   (system "echo -n '('; pkg-config --libs sdl2 glew; echo -n ')'"))))

(library
 (public_name caml-sdl2)
 (name camlSDL2)
 (modes native)
 (public_headers
  (glob_files include/*.h))
 (foreign_stubs
  (language c)
  (names
   rect
   pixel
   hints
   keycode
   error
   blendmode
   scalemode
   surface
   init
   timer
   events
   version
   render
   rwops
   power
   mouse
   keyboard
   audio
   clipboard
   cpuinfo
   filesystem
   joystick
   video
   platform)
  (flags
   :standard
   (:include c_flags.sexp)))
 (c_library_flags
  (:include c_library.sexp)))
